import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root,'dist');
fs.rmSync(dist,{recursive:true,force:true}); fs.mkdirSync(dist,{recursive:true});
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const repo = 'https://github.com/levco/crebench';
const caseRoot = path.join(root,'cases/public/harbor-court-001');
const key = JSON.parse(fs.readFileSync(path.join(caseRoot,'answer-key.json')));
const manifest = JSON.parse(fs.readFileSync(path.join(caseRoot,'manifest.json')));
for (const [name,hash] of Object.entries(manifest.sha256)) {
  const actual = crypto.createHash('sha256').update(fs.readFileSync(path.join(caseRoot,name))).digest('hex');
  if (actual !== hash) throw new Error(`Public case drift: ${name}`);
}
const value = name => key.fields[name].value;
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const nav = [['index','Overview'],['tasks','Tasks'],['method','Method'],['results','Results'],['reproduce','Reproduce']];
function page(id,title,body) {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | CRE Bench by Lev</title><meta name="description" content="An open evaluation project for AI on commercial real estate documents, financial analysis, underwriting models and OMs. Development preview with reproducible public examples."><meta name="theme-color" content="#173248"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="shell"><header class="nav"><a class="brand" href="/">CRE Bench<small>by Lev</small></a><nav aria-label="Main">${nav.map(([slug,label])=>`<a href="/${slug==='index'?'':slug+'.html'}" ${id===slug?'aria-current="page"':''}>${label}</a>`).join('')}<a href="${repo}">GitHub</a></nav></header><main id="main">${body}</main><footer class="footer"><span>Created and published by Lev. Open-source development preview.</span><span><a href="/governance.html">Ownership &amp; governance</a> &nbsp; <a href="${repo}/blob/main/LICENSE">MIT license</a> &nbsp; <a href="${repo}/issues">Report an issue</a></span></footer></div></body></html>`;
  fs.writeFileSync(path.join(dist,id+'.html'),html);
}
const status = '<span class="status">Development preview · Pilot evidence available</span>';
const head = (title,description)=>`<header class="page-head">${status}<h1>${title}</h1><p>${description}</p></header>`;
function sourceTable(headers,rows,highlight=[]) {
  return `<div class="source-scroll"><table class="source-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr${highlight.includes(i)?' class="highlight"':''}>${r.map((v,j)=>`<td${j===r.length-1?' class="num"':''}>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
const t12Rows = fs.readFileSync(path.join(caseRoot,'t12.csv'),'utf8').trim().split('\n').slice(1).map((r,i)=>{const [label,kind,n]=r.split(',');return [i+2,label,money(Number(n))]});
const rollRows = fs.readFileSync(path.join(caseRoot,'rent-roll.csv'),'utf8').trim().split('\n').slice(1).map(r=>{const [unit,type,area,state]=r.split(',');return [unit,type,state,area]});
function workbench() {return `<section class="workbench" aria-label="Interactive worked example"><div class="bench-top"><strong>Inside the benchmark: Harbor Court</strong><span class="pill">Fictional public example</span></div><div class="tabs" role="tablist" aria-label="Example stages"><button id="tab-read" class="tab" role="tab" aria-selected="true" aria-controls="panel-read">Read the financials</button><button id="tab-reconcile" class="tab" role="tab" aria-selected="false" aria-controls="panel-reconcile" tabindex="-1">Resolve a conflict</button><button id="tab-size" class="tab" role="tab" aria-selected="false" aria-controls="panel-size" tabindex="-1">Size the loan</button></div>
<div id="panel-read" role="tabpanel" aria-labelledby="tab-read"><div class="evidence-grid"><div class="source-panel"><div class="source-title"><b>t12.csv</b><span>Annual operating statement</span></div>${sourceTable(['Line','Account','Amount'],t12Rows,[0,1,2])}</div><div class="answer-panel"><h2>Can it get to the right NOI?</h2><p>The answer depends on classification and arithmetic. Capital expenditures and debt service stay outside operating expenses.</p><div class="answer-value">${money(value('noi'))}</div><div class="equation">${money(value('operating_revenue'))} revenue − ${money(value('operating_expenses'))} expenses</div><ul class="check-list"><li>Abatements reduce operating revenue.</li><li>Reimbursements remain in revenue.</li><li>The calculation reconciles to the source.</li><li>Every value has a checkable location.</li></ul><a href="/example.html">Inspect the full answer and source packet</a></div></div></div>
<div id="panel-reconcile" role="tabpanel" aria-labelledby="tab-reconcile" hidden><div class="evidence-grid"><div class="source-panel"><div class="source-title"><b>rent-roll.csv</b><span>As of December 31, 2025</span></div>${sourceTable(['Unit','Type','Status','Area, sf'],rollRows,[3])}</div><div class="answer-panel"><h2>A signed lease is still pending.</h2><p>The summary counts unit 104 as occupied. Its lease starts February 1, 2026. The in-place calculation must exclude it.</p><div class="answer-value">9 of 12 units</div><div class="equation">${value('unit_occupancy_pct')}% unit occupancy · ${value('area_occupancy_pct')}% area occupancy</div><ul class="check-list"><li>Preserve the source’s reported 10 occupied units.</li><li>Use 9 active leases for in-place occupancy.</li><li>Show occupied counts for each unit type.</li><li>Flag the disagreement and record the resolution.</li></ul><p>Historical rental income differing from current annualized rent is not, by itself, a conflict.</p></div></div></div>
<div id="panel-size" role="tabpanel" aria-labelledby="tab-size" hidden><div class="evidence-grid"><div class="source-panel"><div class="source-title"><b>sizing-inputs.json</b><span>Interest-only loan</span></div>${sourceTable(['Input','Value'],[['Value','$2,400,000'],['Normalized NOI','$150,000'],['Maximum LTV','65%'],['Minimum DSCR','1.25×'],['Minimum debt yield','9%']])}<label class="range-label" for="interest-rate"><span>Change the annual interest rate</span><output id="rate-label">7.00%</output></label><input id="interest-rate" type="range" min="5" max="10" step="0.25" value="7"><p class="subtle">Illustrative sensitivity, calculated in your browser. It is not a model run.</p></div><div class="answer-panel"><h2>Does the model find the constraint?</h2><p>Maximum proceeds is the smallest of the three loan limits. Move the rate to see when the binding constraint changes.</p><div class="answer-value" id="loan-limit">${money(value('max_loan'))}</div><p id="binding">LTV is the binding constraint.</p><table><tbody><tr><td>LTV limit</td><td class="num">${money(value('ltv_limit'))}</td></tr><tr><td>DSCR limit</td><td class="num" id="dscr-limit">${money(value('dscr_limit'))}</td></tr><tr><td>Debt-yield limit</td><td class="num">${money(value('debt_yield_limit'))}</td></tr></tbody></table><div class="equation">DSCR limit = NOI ÷ (minimum DSCR × annual interest rate)</div></div></div></div><div class="bench-footer"><span>Worked solution, not AI output. Public key; independent CRE review pending.</span><a href="/reproduce.html">Run the checks locally</a></div></section>`}
page('index','AI, measured against the work',`<section class="hero"><div>${status}<h1>AI, measured against<br>the work.</h1></div><div><p>How well can AI read a deal, understand the financials, and produce work you can use?</p><p>CRE Bench makes that question testable—with source documents, explicit checks, and inspectable outputs.</p><div class="actions"><a class="button primary" href="/tasks.html">Explore the tasks</a><a class="button" href="${repo}">View the source</a></div></div></section>${workbench()}<section class="section"><div class="section-heading"><h2>Follow the work from source to output.</h2><p>Each layer reveals a different failure. End-to-end tests will show how those failures carry into the final deliverable.</p></div><div class="stages"><article class="stage"><h3>Read the documents</h3><p>Extract facts from operating statements, rent rolls, leases and amendments. Locate the evidence and recognize what is missing.</p><div class="examples">Ingestion · Accuracy · Source references</div></article><article class="stage"><h3>Understand the financials</h3><p>Reconcile periods, resolve conflicting figures, normalize income and calculate the financing constraints correctly.</p><div class="examples">NOI · Occupancy · Debt sizing</div></article><article class="stage"><h3>Produce usable work</h3><p>Build underwriting models that recalculate and OMs whose numbers, narrative and rendered pages stand up to review.</p><div class="examples">Underwriting workbooks · Offering memoranda</div></article></div></section><aside class="callout"><div><h2>Open enough to check.</h2><p>The public example, answer key, grader and website are available under an MIT license. Real-case evaluation and model results come after independent review and a frozen protocol.</p></div><a class="button" href="/method.html">Read the method</a></aside>`);
const tasks = [
 ['ingestion','Operating statements & rent rolls','Extract the facts, preserve the source, and distinguish a real discrepancy from a false alarm.','CSV/JSON example available','27 fields with financial and source-reference checks.',true],
 ['ingestion','Leases & amendments','Identify obligations, rent steps and governing amendments without inventing missing terms.','Planned','Source clauses, precedence and critical dates.',false],
 ['understanding','Financial reconciliation','Normalize income, separate units from area, and explain which conflicting figure should be used.','Public example available','NOI arithmetic, occupancy and pending-lease resolution.',true],
 ['understanding','Debt sizing','Calculate proceeds under each constraint and identify the one that binds.','Public example available','Interest-only LTV, DSCR and debt-yield checks.',true],
 ['outputs','Underwriting models','Build a native workbook whose formulas and sensitivities respond correctly when assumptions change.','Validator planned','Formula structure, recalculation and cash-flow reconciliation.',false],
 ['outputs','Offering memoranda','Turn a packet into a coherent, source-grounded document that a professional can review.','Validator planned','Financial accuracy, rendered readability and professional usability.',false]
];
page('tasks','Task families',`${head('The work we are testing.','A focused first release for CRE debt and financing. Implementation status is shown separately from performance; the examples below are not scored model evaluations.')}<div class="filters" aria-label="Filter task families">${[['all','All tasks'],['ingestion','Document ingestion'],['understanding','Financial understanding'],['outputs','Work products']].map(([id,label])=>`<button class="filter" data-filter="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div><p id="task-count" class="screen-reader" aria-live="polite">6 task families shown</p><section class="task-list">${tasks.map(([layer,name,desc,state,measure,ready])=>`<article class="task-row" data-layer="${layer}"><div class="family">${({ingestion:'Document ingestion',understanding:'Financial understanding',outputs:'Work products'})[layer]}</div><div><h2>${esc(name)}</h2><p>${esc(desc)}</p></div><div><span class="state ${ready?'ready':''}">${state}</span><p>${esc(measure)}</p>${ready?'<a href="/example.html">Inspect the shared example</a>':''}</div></article>`).join('')}</section>`);
page('method','Methodology',`${head('A result should survive inspection.','Measure the facts, calculations and usefulness of the work. Keep the evidence behind every claim accessible.')}<article class="content"><p class="note">Methodology 0.1 is a development protocol. The public grader covers one synthetic example. Model adapters, authentic-case qualification, artifact validators and independent review are still to come.</p><h2>Separate reading, reasoning and output.</h2><p>Component tests control the intermediate facts to isolate a capability. End-to-end tests begin with original documents and evaluate the finished work. Models in a common harness and production products have separate comparisons with disclosed tools and data.</p><h2>Start with checkable answers.</h2><p>Each case needs source locations, calculation rules, explicit tolerances and an independently reviewed key. Correct values and correct calculations are separate checks. False conflicts, missing facts and unsupported assumptions must remain visible.</p><h2>Test more than one familiar packet.</h2><p>Build coverage across property types, document producers, file quality and transaction structure. Keep a deal and its variants in one split. Public examples demonstrate the method; they never count as hidden-set evidence.</p><h2>Inspect the work product.</h2><p>Underwriting should pass formula checks and recalculate under changed assumptions. OMs should carry grounded figures and render clearly. Professional review will assess usability and correction effort alongside automated checks.</p><h2>Freeze before the scored run.</h2><p>Record model versions, prompts, tools, budgets, inputs, graders and output hashes. Preserve failures and disclose infrastructure replacements. Report all eligible systems and cases under the preregistered rules.</p><h2>Report the limits with the result.</h2><p>Publish task-level accuracy, material errors, reliability, cost and time. Compare systems on the same cases and account for related deals when estimating uncertainty. A high check count is not a large independent sample.</p><div class="actions"><a class="button primary" href="${repo}/blob/main/docs/methodology.md">Read the full protocol</a><a class="button" href="/governance.html">Ownership and corrections</a></div></article>`);
page('results','Results',`${head('The first pilot is inspectable.','Nine real API calls on one public synthetic case. Development evidence, with failures preserved; no leaderboard or real-world accuracy claim.')}<section class="empty"><h2>9 responses. 0 valid JSON submissions.</h2><p>Three repetitions each for MiMo V2.5, MiMo V2.5 Pro and Ling 3.0 Flash Sante returned HTTP 200. All failed the frozen strict JSON contract. Financial correctness was not scored: this is a submission-reliability finding, not a claim of zero financial accuracy.</p><div class="actions"><a class="button primary" href="${repo}/blob/main/experiments/2026-09-06-accessible-pilot/RESULTS.md">Inspect every attempt</a><a class="button" href="${repo}/tree/main/experiments/2026-09-06-accessible-pilot">Raw answers and frozen protocol</a></div></section><article class="content"><h2>What this tells us about the benchmark</h2><p>Strict formatting can prevent us from measuring financial understanding. The next protocol will separate response-contract compliance from financial correctness. These original attempts are retained without repair or favorable-run selection.</p><h2>What was tested</h2><p>One fictional rent roll, operating statement, source summary and interest-only sizing brief, supplied as text. Three accessible models were selected before execution based on access, not as a representative frontier comparison. A separate premium-model experiment stopped on an access rejection before any model answer.</p><p>All nine attempts, durations, returned token usage and gateway costs are retained. Repeated runs are not independent cases. The answer key is public and independent practitioner review is pending.</p><h2>Lev product calibration</h2><p>A separate native product pilot is testing file ingestion, Index facts, financial analysis and generated artifacts. Product results will be reported separately, with recovery steps and defaults disclosed. Lev owns this project; its product assessment is not independent.</p><h2>Still required before a leaderboard</h2><p>Reviewed cases across real document formats, independent case counts, artifact validators, disclosed tools, and comparable evaluation conditions. No model or product ranking is supported by this pilot.</p></article>`);
const files = [...manifest.system_inputs,'answer-key.json','reference-answer.json','manifest.json'];
page('example','Worked example',`${head('One packet. Every answer inspectable.','Harbor Court is an original fictional example. It connects document extraction, conflict resolution and debt sizing; it is not a representative corpus or a hidden test.')} ${workbench()}<div class="two-col"><article class="content"><h2>Download the packet</h2><ul class="file-list">${files.map(f=>`<li><a href="/examples/harbor-court-001/${f}">${f}</a><small>${f.includes('answer')?'Public answer':f==='manifest.json'?'Hashes and provenance':'Case material'}</small></li>`).join('')}</ul></article><article class="content"><h2>What the grader can establish</h2><p>Value agreement, the declared source-reference sets, true and false discrepancy IDs, NOI self-consistency, and whether proceeds equal the minimum loan limit.</p><h2>What it cannot establish yet</h2><p>General PDF or scan ingestion, quality of a written explanation, a functioning underwriting workbook, rendered OM quality, or performance on real deals. Independent practitioner qualification is pending.</p><a class="button" href="/reproduce.html">Reproduce the checks</a></article></div>`);
page('reproduce','Reproduce',`${head('Run it. Inspect it. Challenge it.','A small public example, a disclosed answer key and deterministic checks. No API key or model subscription is needed to reproduce this release.')}<article class="content"><h2>Start from the source</h2><p>Requires Python 3.11+ and Node 20+. This initial slice has no third-party runtime dependencies.</p><pre><code>git clone https://github.com/levco/crebench.git
cd crebench
python3 -m unittest discover -s tests -v
python3 -m crebench verify cases/public/harbor-court-001
python3 -m crebench grade cases/public/harbor-court-001 \\
  cases/public/harbor-court-001/reference-answer.json
npm run build
python3 -m http.server 4173 --directory dist</code></pre><p class="note">The supplied answer is a worked solution, not model output. Its grade is a development check and must not be cited as an AI benchmark score.</p><h2>Check a different answer</h2><p>Use the source packet and output contract to produce your own answer.json. Pass that path to the grade command. Add <code>--record result.json</code> to write a new record with input, output and grader hashes. Existing records cannot be overwritten.</p><h2>Report a problem</h2><p>Identify the case and criterion, show the expected and observed behavior, and include a minimal reproduction. Please keep customer documents and protected information out of public issues.</p><div class="actions"><a class="button primary" href="${repo}/issues">Open a GitHub issue</a><a class="button" href="${repo}/blob/main/CONTRIBUTING.md">Contribution guide</a></div></article>`);
page('governance','Ownership and governance',`${head('Published by Lev. Open to scrutiny.','Clear ownership, visible conflicts and a correction process are part of the benchmark.')}<article class="content"><h2>Who owns the project</h2><p>Lev creates, funds and publishes CRE Bench. Lev may also participate in its product comparisons. We do not describe this as an independent evaluation of Lev. External reviewers and their qualifications will be named when appointed.</p><h2>What is open</h2><p>The original code, website, documentation and fictional public example are MIT licensed. The license does not grant trademark rights. Customer documents, credentials and protected answer keys are not included.</p><h2>What a public score will require</h2><p>Reviewed cases, a frozen protocol, complete eligible results, disclosed tool access and provenance. Before scored execution, the publication policy will commit to reporting unfavorable findings as well as favorable ones.</p><h2>How corrections work</h2><p>A verified key or grader error affects every applicable system under the same rule. Preserve the original release, document the error and publish a new version with its impact. No selective score repair.</p><h2>Contributors and provenance</h2><p>The initial scope was informed by an earlier methodology engagement with The AI Consulting Network. This release contains an original implementation and synthetic example; it does not redistribute the consultant’s private materials or imply his endorsement or validation.</p><a class="button" href="${repo}/blob/main/docs/governance.md">Full governance policy</a></article>`);
fs.writeFileSync(path.join(dist,'404.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>Page not found | CRE Bench</title><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><main class="shell page-head"><h1>Page not found.</h1><p>This address is not part of the current release.</p><a class="button" href="/">Return to CRE Bench</a></main></html>`);
for(const f of ['style.css','app.js'])fs.copyFileSync(path.join(root,'site',f),path.join(dist,f));
fs.writeFileSync(path.join(dist,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><rect width="48" height="48" rx="10" fill="#173248"/><path d="M32 14H20a10 10 0 0 0 0 20h12M32 24H22" fill="none" stroke="white" stroke-width="4"/></svg>');
fs.mkdirSync(path.join(dist,'examples/harbor-court-001'),{recursive:true});
for(const f of files)fs.copyFileSync(path.join(caseRoot,f),path.join(dist,'examples/harbor-court-001',f));
fs.writeFileSync(path.join(dist,'release.json'),JSON.stringify({version:'0.1.0',status:'development_preview',publisher:'Lev',model_results:[],development_experiments:[{id:'2026-09-06-accessible-pilot',attempts:9,valid_submissions:0,financial_accuracy:null,leaderboard_eligible:false}],public_examples:[manifest.case_id],source:repo},null,2)+'\n');
fs.writeFileSync(path.join(dist,'robots.txt'),'User-agent: *\nAllow: /\n');
console.log('Built 8 pages, one public example and development pilot links. No leaderboard scores.');
