"""Original classification probes grounded in dated public program evidence."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'benchmarks/lender-qualification-v1';BASE.mkdir(exist_ok=True)
source=[{'id':'fannie-conventional','title':'Fannie Mae Conventional Properties Term Sheet','url':'https://multifamily.fanniemae.com/financing-options/conventional-properties-term-sheet','retrieved_at':'2026-09-07','publication_date':None,'summary':'Conventional first-lien acquisition/refinance financing for existing stabilized multifamily with at least five units. Maximum LTV 80%; minimum DSCR 1.25x. Typical stabilized occupancy is 90% for 90 days; pre-stabilized commitments can receive case-by-case consideration. Nonrecourse execution is available for most loans over $750,000 with standard carve-outs. Guidelines do not establish approval of a specific borrower.'},{'id':'freddie-transition','title':'Freddie Mac Conventional Small launch','url':'https://freddiemac.gcs-web.com/news-releases/news-release-details/freddie-mac-multifamily-announces-launch-integrated-conventional/','retrieved_at':'2026-09-07','publication_date':'2026-04-15','summary':'Freddie Mac announced Conventional Small for loans from $2 million to $10 million on April 15, 2026. Applications under the former Small Balance Loan program were accepted through April 30, 2026. The announcement does not state a complete set of current underwriting criteria or promise approval.'}]
probes=[
 ('lender-01','New $3 million application on September 7, 2026 to the former Freddie Mac Small Balance Loan program. Is that named legacy program open for a new application?','not_eligible','freddie-transition','Legacy application transition ended April 30.'),
 ('lender-02','$1.5 million requested through Freddie Mac Conventional Small on September 7, 2026. Does the disclosed product amount range support it?','not_eligible','freddie-transition','Below disclosed $2 million lower bound.'),
 ('lender-03','$5 million requested through Freddie Mac Conventional Small on September 7, 2026. Does the amount meet the disclosed range, and does that alone establish full eligibility?','amount_in_range_other_criteria_unverified','freddie-transition','Amount fits; other eligibility criteria are not supplied.'),
 ('lender-04','Fannie Mae conventional term-sheet fit: stabilized 40-unit multifamily, LTV 75%, DSCR 1.30, occupied 95% for 120 days, acquisition; US single-asset borrower. Credit and reports remain unreviewed.','fits_disclosed_property_financial_criteria_approval_unverified','fannie-conventional','Fits stated tested criteria; approval remains unverified.'),
 ('lender-05','Fannie Mae conventional term-sheet fit: stabilized 3-unit residential property, LTV 60%, DSCR 1.5. No exception or other program is in the supplied source.','not_eligible','fannie-conventional','Below five-unit property minimum.'),
 ('lender-06','Fannie Mae conventional term-sheet fit: stabilized 50-unit multifamily, requested LTV 85%, DSCR 1.30. No leverage exception is documented.','not_eligible','fannie-conventional','Exceeds the disclosed 80% maximum.'),
 ('lender-07','Fannie Mae conventional term-sheet fit: 60-unit multifamily, occupancy 87% for 45 days, LTV 70%, DSCR 1.30. Does the source categorically prohibit a commitment or permit case-by-case consideration?','case_by_case_not_standard_stabilized','fannie-conventional','Typical stabilization is unmet; the source explicitly permits case-by-case pre-stabilized commitments.'),
 ('lender-08','Fannie Mae conventional term-sheet fit: stabilized 40-unit multifamily, LTV 70%, debt service not supplied and DSCR cannot be established. Can it be called financially qualified?','insufficient_information','fannie-conventional','Missing DSCR prevents complete financial qualification.'),
]
common='''You are reviewing financing fit, not making a credit decision. Use only the two provided public-source summaries and their cited authoritative pages as the fixed evidence packet. Do not treat a typical guideline as an absolute ban where the source explicitly allows exceptions. Distinguish a disclosed amount range from full eligibility and from actual approval. No outreach or CRM changes. Return a JSON object with classification, reason, source_ids (array), missing_information (array), and approved (always false unless explicit actual approval evidence exists). Use one classification from: not_eligible; amount_in_range_other_criteria_unverified; fits_disclosed_property_financial_criteria_approval_unverified; case_by_case_not_standard_stabilized; insufficient_information.\n'''
for cid,prompt,expected,source_id,reason in probes:
 d=BASE/'cases'/cid;d.mkdir(parents=True,exist_ok=True)
 (d/'brief.md').write_text(common+'\nBusiness question: '+prompt+'\n\nEvidence packet:\n'+json.dumps(source,indent=2)+'\n')
 (d/'reference.json').write_text(json.dumps({'classification':expected,'source_id':source_id,'approved':False,'reason':reason,'review_status':'independent-review-pending'},indent=2)+'\n')
(BASE/'sources.json').write_text(json.dumps(source,indent=2)+'\n')
(BASE/'README.md').write_text('''# Dated lender qualification probes\n\nEight original business questions about current versus retired programs, loan size, minimum property scale, leverage, missing coverage, and documented exceptions. This tests evidence-based program qualification. It is not a test of the native lender-directory ranking or a statement that any real loan has been approved. The source summaries are short original paraphrases with links; the Freddie notice is dated, while the Fannie page is undated and captured as a 2026-09-07 snapshot. Independent professional qualification is pending.\n\nRun native Lev and GPT-5 / Opus 5 as supplied-source conditions; preserve exact prompts and every outcome. Three trials per case are targeted, with one pass through all cases before repeats. The same borrower/property facts and allowed evidence are supplied. Grade substantive classification, source selection, unwarranted approval, and whether the explanation respects documented uncertainty. Explanation adequacy requires review; matching an enum alone is not a professional score. A separate native lender-match test must record product suggestions and its own evidence before directory superiority can be claimed.\n''')
print(json.dumps({'lender_probes':len(probes),'public_sources':len(source)}))
