import fs from 'node:fs';
import path from 'node:path';
const repo='https://github.com/levco/crebench';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const names={'lev/native':'Lev Agent','openai/gpt-5':'GPT-5 agent','anthropic/claude-opus-5':'Opus 5 agent'};
const colors={'lev/native':'#08331F','openai/gpt-5':'#3B69BC','anthropic/claude-opus-5':'#B56750'};
const num=x=>typeof x==='number'?new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(x):x===null?'Unknown':String(x??'Missing');
const table=(head,rows)=>`<div class="source-scroll"><table class="wf-table"><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
export const knownCost=r=>typeof r.cost_usd==='number'?r.cost_usd:typeof r.known_partial_cost_usd==='number'?r.known_partial_cost_usd:null;
export const costLabel=r=>typeof r.cost_usd==='number'?'$'+r.cost_usd.toFixed(3):typeof r.known_partial_cost_usd==='number'?'≥ $'+r.known_partial_cost_usd.toFixed(3):'Unknown';
export function executiveReadout(data){
 const lev=data.runs.filter(r=>r.system==='lev/native');
 const financial=lev.reduce((n,r)=>n+(r.field_scores?.financial?.passed??0),0);
 const clean=lev.filter(r=>r.review?.memo?.length===10&&r.review.memo.every(c=>c.passed)).length;
 return `<section class="section wf-readout"><div class="section-heading"><span class="section-index">The executive readout</span><h2>Strong math. Work products still need review.</h2></div><div class="wf-findings"><article><span class="wf-kpi">${financial}/132</span><h3>Lev financial checks passed</h3><p>All six cases correctly size the loan, separate NOI from NCF, apply lender conventions and calculate the combined downside.</p></article><article><span class="wf-kpi">${clean}/6</span><h3>Lev memos pass every check</h3><p>Correct tables do not guarantee correct narrative. Two memos reverse cash-out into cash-in; others misstate payments, rollover, formulas or risk. Five have layout defects.</p></article><article><span class="wf-kpi">18</span><h3>Changed-input Lev checks passed</h3><p>Cap rate, sizing rate and income changes recalculate correctly in every Lev workbook. Four workbooks still contain formula errors in explanation cells.</p></article></div><p class="wf-takeaway">This release supports confidence in Lev’s numerical analysis on these packets. It does <strong>not yet establish an overall Lev advantage</strong>. Compare the general agents below and inspect the delivered files before drawing a buying conclusion.</p></section>`;
}
export function evidencePanel(data){
 return `<section class="section"><div class="section-heading"><h2>Can a reviewer find the supporting source?</h2><p>Correct source facts and correct source locations are separate checks. Missing locations fail this measure even when the value is right.</p></div><div class="wf-evidence-bars">${Object.keys(names).map(m=>{const r=data.runs.filter(x=>x.system===m&&x.track!=='direct');const ready=r.length===6&&r.every(x=>x.evidence_score);const passed=r.reduce((n,x)=>n+(x.evidence_score?.passed??0),0);return `<div><strong>${names[m]}</strong><div class="wf-bar-track">${ready?`<span style="width:${passed/102*100}%;background:${colors[m]}"></span>`:''}</div><span>${ready?`${passed}/102 · ${(passed/102*100).toFixed(1)}%`:'Review pending'}</span></div>`;}).join('')}</div><p class="subtle">The scale runs from 0 to 100%. Final analysis citations, including explicit table context and named source records, are checked against original files. Workbook and memo citations have their own acceptance checks. <a href="${repo}/blob/main/docs/workflow-evidence-review-2026-09-06.md">Review the exact interpretation</a>.</p></section>`;
}
export function reviewDetails(r){
 if(!r.review)return '';
 const claims=r.review.critical_claims??[];
 const findings=r.review.findings??[];
 const checks=[...(r.workbook_audit?.checks??[]).map(c=>({...c,kind:'Workbook',rationale:typeof c.detail==='string'?c.detail:JSON.stringify(c.detail)})),...(r.review.workbook??[]).map(c=>({...c,kind:'Workbook'})),...(r.review.memo??[]).map(c=>({...c,kind:'Memo'}))];
 return `${claims.length?`<div class="wf-claims"><h4>Material claims to inspect</h4>${claims.map(c=>`<details><summary>${esc(c.location)} — ${esc(c.claim)}</summary><p><strong>Source-supported finding:</strong> ${esc(c.correct_calculation)}</p><p>${esc(c.rationale)}</p></details>`).join('')}</div>`:''}${findings.length?`<details><summary>All review findings (${findings.length})</summary><ul>${findings.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></details>`:''}${checks.length?`<details><summary>Every artifact acceptance check (${checks.filter(c=>c.passed).length}/${checks.length})</summary>${table(['Work product','Check','Outcome','Evidence'],checks.sort((a,b)=>a.kind.localeCompare(b.kind)||a.rubric_check-b.rubric_check).map(c=>[c.kind,c.rubric_check,`<span class="${c.passed?'wf-pass':'wf-loss'}">${c.passed?'Pass':'Fail'}</span>`,esc(c.rationale)+(c.evidence?'<br>'+esc(c.evidence):'')]))}</details>`:''}`;
}
export function fieldExplorer(rows){
 return `<section class="section wf-explorer" data-explorer><h2>Inspect every reported value</h2><p>The same 39 source and financial checks apply to every system. Open a row to see the response citation and review rationale. Direct controls are labeled separately.</p><div class="wf-explorer-controls"><label>System<select data-system-select><option value="all">All systems and tracks</option>${rows.map((r,i)=>`<option value="${i}">${esc(names[r.system])}${r.track==='direct'?' · direct API':''}</option>`).join('')}</select></label><label><input type="checkbox" data-failures-only> Only value or citation failures</label></div><p aria-live="polite" data-visible-count></p>${rows.map((r,i)=>r.quality_status==='excluded_infrastructure'?'':`<div data-system-block="${i}"><h3>${esc(names[r.system])}${r.track==='direct'?' · direct API control':''}</h3>${(r.field_checks??[]).map(c=>{const ev=r.review?.evidence?.find(e=>e.field===c.field);const fail=!c.passed||ev?.passed===false;return `<details class="wf-field" data-field-row data-system="${i}" data-failed="${fail}"><summary><code>${esc(c.field)}</code><span class="${c.passed?'wf-pass':'wf-loss'}">${c.passed?'Value passed':'Value failed'}</span>${ev?`<span class="${ev.passed?'wf-pass':'wf-loss'}">${ev.passed?'Source supported':'Citation failed'}</span>`:c.group==='extraction'?'<span>Source review pending</span>':''}</summary><dl><dt>Reported</dt><dd>${esc(num(c.actual))}</dd><dt>Expected</dt><dd>${esc(num(c.expected))}</dd><dt>Response evidence</dt><dd>${esc((Array.isArray(c.evidence)?c.evidence.map(e=>typeof e==='string'?e:JSON.stringify(e)).join(' · '):typeof c.evidence==='string'?c.evidence:JSON.stringify(c.evidence))||'No inline location supplied')}</dd>${c.calculation?`<dt>Calculation supplied</dt><dd>${esc(c.calculation)}</dd>`:''}${ev?`<dt>Review</dt><dd>${esc(ev.rationale)}</dd><dt>Checked source</dt><dd>${esc(ev.verified_source_location)}</dd>${ev.response_context?.length?`<dt>Scoped response context</dt><dd>${ev.response_context.map(esc).join('<br>')}</dd>`:''}`:''}</dl></details>`;}).join('')}</div>`).join('')}</section>`;
}
export function costTable(data){
 const rows=[];
 for(const track of ['lev_native','agent','direct'])for(const model of Object.keys(names)){
  const runs=data.runs.filter(r=>r.track===track&&r.system===model);if(!runs.length)continue;
  const known=runs.map(knownCost);const sum=known.reduce((n,x)=>n+(x??0),0);const complete=runs.every(r=>typeof r.cost_usd==='number');
  rows.push([esc(names[model])+(track==='direct'?' · direct':''),`${runs.filter(r=>r.status==='completed').length}/6`,`${complete?'':'≥ '}$${sum.toFixed(3)}`,`${complete?'':'≥ '}$${(sum/6).toFixed(3)}`,model==='lev/native'?'Matched native chat traces; estimated inference':'Gateway-reported inference'+(complete?'':'; rejected-attempt billing unreported')]);
 }
 return table(['System / track','Completed','Six-case inference','Per planned case','Measurement'],rows)+'<p class="subtle">A ≥ amount is the known subtotal; unavailable cost is not silently zero. <a href="https://github.com/levco/crebench/blob/main/experiments/2026-09-06-workflow-development/costs.json">Separate adapter-development costs</a> are excluded from scored runs. Administrative credit waiting is excluded from resumed active latency and preserved in execution records.</p>';
}
export function additionalPages({page,head,limits,experiment}){
 page('reproduce','Reproduce the workflow checks',`${head('Inspect the files. Recompute the findings.','Open source inputs, keys, responses and artifact audits. No model API is needed to check recorded numerical results.')}<article class="content"><h2>Regrade all recorded answers</h2><p>Python 3.11+ and Node 20+ are required. Install the small review dependency set, then reproduce the uniform formatting correction and published scores.</p><pre><code>git clone https://github.com/levco/crebench.git
cd crebench
python3 -m pip install -r requirements-review.txt
python3 tools/collect-workflow-results.py ${experiment}
python3 -m unittest discover -s tests -v
npm run build
npm run check:site</code></pre><h2>Recalculate actual Excel files</h2><p>Install LibreOffice and make <code>soffice</code> available on PATH. The public replay checks original workbooks and the published changed-input copies against independent financial expectations. It verifies each edited cell and records your local engine version.</p><pre><code>python3 tools/replay-workflow-audits.py ${experiment} \\
  --output work/independent-replay</code></pre><p>The scored run used LibreOfficeDev 26.8.0.0.alpha0. Engine differences are recorded, not hidden. The replay reads published XLSX files without rewriting their formulas.</p><h2>Run the models again</h2><p>The frozen runner, complete prompts, tool schemas, context transforms and model IDs are published in <a href="${repo}/tree/main/crebench">crebench/</a>. A new paid run must use a new experiment directory and disclose its own model availability, version and date.</p><p class="note"><strong>Reproduction limit:</strong> The scored general-agent artifact writer used the Codex-bundled <code>@oai/artifact-tool</code> package, which was not available from the public npm registry when checked. Its wrapper source is public, but identical artifact generation currently requires that runtime. The public replay and numerical grader have no dependency on it. Lev’s native backend remains proprietary; its original outputs, operating conditions and sanitized review evidence are public.</p><h2>Challenge a finding</h2><p>Include the case, system, exact criterion and supporting page or cell. Author reviews are open to disagreement. Cite the original output and show the proposed correction; every affected system must be regraded together.</p><a class="button primary" href="${repo}/issues">Open a benchmark issue</a></article>${limits}`);
 page('governance','Ownership and corrections',`${head('Published by Lev. Open to scrutiny.','Lev owns and funds CRE Bench and participates in the evaluation. That conflict is disclosed beside the results.')}<article class="content"><h2>What is public</h2><p>Original fictional packets, the business briefs, answer keys, reference workbooks, evaluation code, website, API execution records, delivered artifacts and author reviews are published under the repository’s MIT license. Trademark rights are excluded. Customer documents, credentials, private account context and Lev internal prompts are excluded.</p><h2>What the scores establish</h2><p>This is a six-case diagnostic release with one fresh attempt per system and case. Sources and keys were frozen before execution, then the outputs received machine-assisted author review. Independent CRE practitioner validation, repeated trials and broader authentic-document qualification remain outstanding. Check counts are not independent deals; no confidence interval or industry-wide superiority claim is made.</p><h2>Corrections with a visible history</h2><ul><li><a href="${repo}/blob/main/docs/workflow-insurance-criterion-2026-09-06.md">Uniform exclusion of the ambiguous insurance-evidence criterion</a></li><li><a href="${repo}/blob/main/docs/workflow-display-normalization-2026-09-06.md">Presentation normalization without financial answer repair</a></li><li><a href="${repo}/blob/main/docs/workflow-evidence-review-2026-09-06.md">Source-location review interpretation and rationale</a></li><li><a href="${repo}/blob/main/docs/workflow-billing-resumption-2026-09-06.md">Exact-context resumption after gateway credit exhaustion</a></li></ul><p>Original records remain available. A correction applies to every affected result, including results unfavorable to Lev.</p><h2>Contributors and provenance</h2><p>The initial scope was informed by a methodology engagement with The AI Consulting Network. This release uses an original implementation and original synthetic cases. It does not redistribute the consultant’s private materials or imply his endorsement. Case authoring and review used AI assistance; no independent practitioner review is claimed.</p><h2>What comes next</h2><p>Independent CRE review of the keys and memo rubric, a larger held-out corpus with permitted authentic layouts, repeated trials, separate Index ingestion evaluation, offering-memorandum tasks, complete cost attribution and a fully public artifact-generation adapter. These are future work, not completed coverage.</p></article>`);
}
